version: "3.8"

networks:
  observability:
    driver: bridge

volumes:
  tempo_data:
  loki_data:
  grafana_data:

services:
  server:
    build: ./build
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.3.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
    restart: unless-stopped
    networks:
      - observability

  loki:
    image: grafana/loki:2.9.6
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    user: "0:0"  # Rodar como root (apenas para testes)
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - observability
